import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import Script from "next/script";
import "../globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import NavBar from "@/app/components/NavBar";
import BottomNav from "@/app/components/BottomNav";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

const outfit = Outfit({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html
      lang={locale}
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        outfit.variable,
      )}
    >
      {/* Runs before hydration to apply the saved theme class, preventing flash */}
      <Script id="theme-init" strategy="beforeInteractive">{`
        (function(){try{
          var t=localStorage.getItem("theme")||"light";
          if(t==="system"){t=window.matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light";}
          document.documentElement.classList.remove("light","dark");
          document.documentElement.classList.add(t);
        }catch(e){}}());
      `}</Script>
      <body className="min-h-full flex flex-col pb-20 md:pb-0">
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableColorScheme={false}
            disableTransitionOnChange
          >
            <NavBar />
            {children}
            <BottomNav />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
